import * as React from 'react';
import styles from './ServerRoomDigitalTwin.module.scss';
import { IServerRoomDigitalTwinProps } from './IServerRoomDigitalTwinProps';
import { IInfraDevice, IInfraRack, IRackPlacement } from '../models/ServerRoomModels';
import { getOccupancy, getRackPlacements, getUsedUnits } from '../utils/rackUtils';

const DetailRows: React.FC<{ rows: { [key: string]: string } }> = ({ rows }) => <dl className={styles.details}>{Object.keys(rows).map((key) => <React.Fragment key={key}><dt>{key}</dt><dd>{rows[key]}</dd></React.Fragment>)}</dl>;

const RightDetailsPanel: React.FC<{ racks: IInfraRack[]; devices: IInfraDevice[]; placements: IRackPlacement[]; selectedRack?: IInfraRack; selectedDevice?: IInfraDevice; settingsOpen: boolean; props: IServerRoomDigitalTwinProps }> = ({ racks, devices, placements, selectedRack, selectedDevice, settingsOpen, props }) => {
  const rackPlacements = selectedRack ? getRackPlacements(selectedRack.id, placements) : [];
  const usedU = getUsedUnits(rackPlacements);
  return <aside className={`${styles.detailsPanel} ${selectedDevice ? styles.deviceDetailActive : ''}`}><section className={styles.detailSection}><h3>{selectedDevice ? 'Gerätedetails' : selectedRack ? 'Rackdetails' : 'Raumübersicht'}</h3>{selectedDevice ? <DetailRows rows={{ Hostname: selectedDevice.hostname, 'IP-Adresse': selectedDevice.ipAddress, Rack: selectedRack ? selectedRack.name : '-', Höheneinheit: placements.filter((p) => p.deviceId === selectedDevice.id)[0] ? `U${placements.filter((p) => p.deviceId === selectedDevice.id)[0].startU}` : '-', Gerätetyp: selectedDevice.type, Hersteller: selectedDevice.vendor, Modell: selectedDevice.model, Standort: selectedRack ? selectedRack.site : 'DC-1 Frankfurt', Raum: selectedRack ? selectedRack.room : 'Raum A', Besitzer: selectedDevice.owner, Seriennummer: selectedDevice.serialNumber, Betriebssystem: selectedDevice.operatingSystem, 'Letztes Update': selectedDevice.lastUpdate, Uptime: selectedDevice.uptime, VLAN: selectedDevice.vlan || 'N/A', 'Warranty Expiry': selectedDevice.warrantyExpiry || 'N/A', 'Maintenance Responsible': selectedDevice.owner, Notes: selectedDevice.notes }} /> : selectedRack ? <DetailRows rows={{ 'Rack name': selectedRack.name, Site: selectedRack.site, Room: selectedRack.room, Row: selectedRack.row, HeightU: `${selectedRack.heightU}U`, 'Used / Free U': `${usedU}U / ${Math.max(selectedRack.heightU - usedU, 0)}U`, 'Device count': `${rackPlacements.length}`, Occupancy: `${getOccupancy(selectedRack, rackPlacements)}%`, Type: selectedRack.type, Width: selectedRack.width, Depth: selectedRack.depth }} /> : <DetailRows rows={{ Site: 'DC-1 Frankfurt', Room: 'Raum A', Racks: `${racks.length}`, Devices: `${devices.length}`, Mode: 'Room Overview', Data: 'Mock documentation values only' }} />}</section>{settingsOpen && <section className={`${styles.detailSection} ${styles.settings}`}><h3>SharePoint Mapping / Admin</h3><p className={styles.settingsIntro}>Production data will be loaded from SharePoint Lists. Preview uses dummy data only.</p><DetailRows rows={{ 'Racks list name': props.racksListName || 'Racks', 'Devices list name': props.devicesListName || 'Devices', 'RackPlacements list name': 'RackPlacements', 'Use dummy data': props.useDummyData ? 'Yes' : 'Yes for preview', 'Visible fields': 'Documentation detail fields', 'Future lists': 'Sites, Rooms, Racks, Devices, RackPlacements, DevicePorts, CableConnections, PowerConnections' }} /><div className={styles.mappingGrid}><div><h3>Column mapping placeholder</h3><p>Rack-ID → rack.id</p><p>height unit → rack.heightU</p><p>U-Position → placement.startU</p><p>Device Type → device.type</p><p>Serial Number → device.serialNumber</p><p>Warranty Expiry → device.warrantyExpiry</p><p>Maintenance Responsible → device.owner</p><p>Future optional: UHeight, Manufacturer, Model, AssetTag, RackSide, MountWidth, HorizontalSlot, Notes</p></div></div></section>}</aside>;
};

export default RightDetailsPanel;
