declare const styles: {
  digitalTwin: string;
  header: string;
  kicker: string;
  headerControls: string;
  workspace: string;
  sidebar: string;
  locationGroup: string;
  roomNav: string;
  rackNav: string;
  active: string;
  rackView: string;
  sectionTitle: string;
  rackTop: string;
  threeHost: string;
  sceneMessage: string;
  fallbackGrid: string;
  fallbackRack: string;
  fallbackUnits: string;
  fallbackDevice: string;
  selectedRack: string;
  selectedDevice: string;
  detailPanel: string;
  settings: string;
  tablePanel: string;
  selectedRow: string;
  details: string;
  [className: string]: string;
};
export default styles;
