declare const styles: {
  digitalTwin: string;
  header: string;
  kicker: string;
  headerControls: string;
  workspace: string;
  sidebar: string;
  locationGroup: string;
  rackNav: string;
  active: string;
  rackView: string;
  sectionTitle: string;
  rackGrid: string;
  rackCard: string;
  selectedRack: string;
  rackTop: string;
  units: string;
  deviceBlock: string;
  detailPanel: string;
  settings: string;
  tablePanel: string;
  selectedRow: string;
  details: string;
  statusHealthy: string;
  statusWarning: string;
  statusCritical: string;
  statusOffline: string;
  [className: string]: string;
};
export default styles;
